---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: rchain-coop
  namespace: dev
spec:
  secretName: tls-letsencrypt-staging
  commonName: rchain-coop.tk
  dnsNames:
    - rchain-coop.tk
    - www.rchain-coop.tk
    # - developer.rchain-coop.tk
    # - blog.rchain-coop.tk
    # - dbadmin.rchain-coop.tk

    # - rchain.coop
    # - www.rchain.coop
    # - developer.rchain.coop
    # - blog.rchain.coop
    # - dbadmin.rchain.coop

  issuerRef:
    name: rchain-coop-staging
    kind: ClusterIssuer
  acme:
    config:
      - http01:
          ingressClass: gce
        domains:
        - rchain-coop.tk
        - www.rchain-coop.tk
        - developer.rchain-coop.tk
        # - blog.rchain-coop.tk
        # - dbadmin.rchain-coop.tk
        # - rchain.coop
        # - www.rchain.coop
        # - developer.rchain.coop
        # - blog.rchain.coop
        # - dbadmin.rchain.coop
    
