---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: rchain-coop
spec:
  secretName: tls-letsencrypt-rchain-coop
  commonName: rchain-coop.cf
  dnsNames:
    - rchain-coop.cf
    - www.rchain-coop.cf
    # - developer.rchain-coop.cf
    - blog.rchain-coop.cf
    - dbadmin.rchain-coop.cf

  issuerRef:
    name: rchain-coop
    kind: ClusterIssuer
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
        - rchain-coop.cf
        - www.rchain-coop.cf
        # - developer.rchain-coop.cf
        - blog.rchain-coop.cf
        - dbadmin.rchain-coop.cf
    
