apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: rchain-coop
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kayvan.kazeminejad@rchain.coop
    privateKeySecretRef:
      name: tls-letsencrypt-rchain-coop
    solvers:
    - http01:
        ingress:
          class: nginx
