apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: rchain-coop
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kayvan.kazeminejad@rchain.coop
    privateKeySecretRef:
      name: tls-letsencrypt-rchain-coop
    http01: {}
