---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rchain-coop
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: www-rchain-coop
spec:
  rules:
  - host: rchain.coop
    http:
      paths:
        - backend:
            serviceName: rchain-coop
            servicePort: 3000
  - host: developer.rchain.coop
    http:
      paths:
        - backend:
            serviceName: developer-rchain-coop
            servicePort: 3000
  - host: blog.rchain.coop
    http:
      paths:
        - backend:
            serviceName: wordpress
            servicePort: 80
  - host: dbadmin.rchain.coop
    http:
      paths:
        - backend:
            serviceName: db-adminer
            servicePort: 8080
