---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-rchain-coop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: dev-rchain-coop-ingress
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: rchain-coop
    nginx.ingress.kubernetes.io/tls-acme: 'true'
    kubernetes.io/tls-acme: 'true'
    ingress.kubernetes.io/force-ssl-redirect: "true"

spec:
  rules:
  - host: rchain-coop.cf
    http:
      paths:
        - backend:
            serviceName: rchain-coop
            servicePort: 3000
  - host: www.rchain-coop.cf
    http:
      paths:
        - backend:
            serviceName: rchain-coop
            servicePort: 3000
  - host: developer.rchain-coop.cf
    http:
      paths:
        - backend:
            serviceName: developer-rchain-coop
            servicePort: 3000
  - host: blog.rchain-coop.cf
    http:
      paths:
        - backend:
            serviceName: wordpress
            servicePort: 80
  - host: dbadmin.rchain-coop.cf
    http:
      paths:
        - backend:
            serviceName: db-adminer
            servicePort: 8080
  - host: rsong.rchain-coop.cf
    http:
      paths:
        - backend:
            serviceName: rsong
            servicePort: 80

  - host: rchain.coop
    http:
      paths:
        - backend:
            serviceName: rchain-coop
            servicePort: 3000
  - host: www.rchain.coop
    http:
      paths:
        - backend:
            serviceName: rchain-coop
            servicePort: 3000
  - host: developer.rchain.coop
    http:
      paths:
        - backend:
            serviceName: developer-rchain-coop
            servicePort: 3000
  - host: blog.rchain.coop
    http:
      paths:
        - backend:
            serviceName: wordpress
            servicePort: 80
  - host: dbadmin.rchain.coop
    http:
      paths:
        - backend:
            serviceName: db-adminer
            servicePort: 8080

  tls:
  - hosts:
      - rchain.coop
      - www.rchain.coop
      - developer.rchain.coop
      - blog.rchain.coop
      - dbadmin.rchain.coop
      - rsong.rchain.coop
      - rchain-coop.cf
      - www.rchain-coop.cf
      - developer.rchain-coop.cf
      - blog.rchain-coop.cf
      - dbadmin.rchain-coop.cf
      - rsong.rchain-coop.cf

    secretName: tls-letsencrypt-rchain-coop
