---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rchain-coop
  namespace: dev
  annotations:
    kubernetes.io/ingress.global-static-ip-name: rchain-coop
    kubernetes.io/ingress.class: gce
    ingress.gcp.kubernetes.io/pre-shared-cert: rchain-coop
    # certmanager.k8s.io/cluster-issuer: rchain-coop
    # kubernetes.io/tls-acme: "true"

spec:
  rules:
  - host: rchain-coop.tk
    http:
      paths:
        - backend:
            serviceName: rchain-coop
            servicePort: 3000
  - host: www.rchain-coop.tk
    http:
      paths:
        - backend:
            serviceName: rchain-coop
            servicePort: 3000

  - host: developer.rchain-coop.tk
    http:
      paths:
        - backend:
            serviceName: developer-rchain-coop
            servicePort: 3000
  - host: blog.rchain-coop.tk
    http:
      paths:
        - backend:
            serviceName: wordpress
            servicePort: 80
  - host: dbadmin.rchain-coop.tk
    http:
      paths:
        - backend:
            serviceName: db-adminer
            servicePort: 8080

  - host: rchain.coop
    http:
      paths:
        - backend:
            serviceName: rchain-coop
            servicePort: 3000
  - host: www.rchain.coop
    http:
      paths:
        - backend:
            serviceName: rchain-coop
            servicePort: 3000
  - host: developer.rchain.coop
    http:
      paths:
        - backend:
            serviceName: developer-rchain-coop
            servicePort: 3000

  - host: blog.rchain.coop
    http:
      paths:
        - backend:
            serviceName: wordpress
            servicePort: 80

  - host: dbadmin.rchain.coop
    http:
      paths:
        - backend:
            serviceName: db-adminer
            servicePort: 8080

  tls:
  - hosts:
      - rchain-coop.tk
      - www.rchain-coop.tk
      - developer.rchain-coop.tk
      - blog.rchain-coop.tk
      - dbadmin.rchain-coop.tk
      - rchain.coop
      - www.rchain.coop
      - developer.rchain.coop
      - blog.rchain.coop
      - dbadmin.rchain.coop
    secretName: tls-letsencrypt-rchain-coop
