---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rchain-coop
  namespace: dev
  annotations:
    kubernetes.io/ingress.global-static-ip-name: www-rchain-coop
    certmanager.k8s.io/cluster-issuer: rchain-coop
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.allow-http: "false"
    nginx.kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - host: rchain.coop
    http:
      paths:
        - backend:
            serviceName: rchain-coop
            servicePort: 3000

  - host: blog.rchain.coop
    http:
      paths:
        - backend:
            serviceName: wordpress
            servicePort: 80

  - host: developer.rchain.coop
    http:
      paths:
        - backend:
            serviceName: developer-rchain-coop
            servicePort: 3000

  - host: rsong.org
    http:
      paths:
        - backend:
            serviceName: rsong-org
            servicePort: 80

  - host: wpdb-rchain-coop.tk
    http:
      paths:
        - backend:
            serviceName: db-adminer
            servicePort: 8080

  tls:
  - hosts:
      - rchain.coop
      - blog.rchain.coop
      - developer.rchain.coop
      - rsong.org
    secretName: tls-secret
