---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rchain-coop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: rchain-coop
    kubernetes.io/ingress.class: ingress
    ingress.gcp.kubernetes.io/pre-shared-cert: rchain-coop
    certmanager.k8s.io/cluster-issuer: rchain-coop
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"

spec:
  rules:
  - host: rchain-coop.tk
    http:
      paths:
        - backend:
            serviceName: rchain-coop
            servicePort: 3000
  - host: www.rchain-coop.cf
    http:
      paths:
        - backend:
            serviceName: rchain-coop
            servicePort: 3000

  - host: developer.rchain-coop.cf
    http:
      paths:
        - backend:
            serviceName: developer-rchain-coop
            servicePort: 3000
  - host: blog.rchain-coop.cf
    http:
      paths:
        - backend:
            serviceName: wordpress
            servicePort: 80
  - host: dbadmin.rchain-coop.cf
    http:
      paths:
        - backend:
            serviceName: db-adminer
            servicePort: 8080

  # - host: rchain.coop
  #   http:
  #     paths:
  #       - backend:
  #           serviceName: rchain-coop
  #           servicePort: 3000
  # - host: www.rchain.coop
  #   http:
  #     paths:
  #       - backend:
  #           serviceName: rchain-coop
  #           servicePort: 3000
  # - host: developer.rchain.coop
  #   http:
  #     paths:
  #       - backend:
  #           serviceName: developer-rchain-coop
  #           servicePort: 3000

  # - host: blog.rchain.coop
  #   http:
  #     paths:
  #       - backend:
  #           serviceName: wordpress
  #           servicePort: 80

  # - host: dbadmin.rchain.coop
  #   http:
  #     paths:
  #       - backend:
  #           serviceName: db-adminer
  #           servicePort: 8080

  tls:
  - hosts:
      - rchain-coop.cf
      - www.rchain-coop.cf
      - developer.rchain-coop.cf
      - blog.rchain-coop.cf
      - dbadmin.rchain-coop.cf
    secretName: tls-letsencrypt-rchain-coop
