---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rchain-coop
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: www-rchain-coop
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: rchain-coop.tk
    http:
      paths:
        - backend:
            serviceName: rchain-coop
            servicePort: 3000

  - host: blog-rchain-coop.tk
    http:
      paths:
        - backend:
            serviceName: wordpress
            servicePort: 80

  - host: developer-rchain-coop.tk
    http:
      paths:
        - backend:
            serviceName: developer-rchain-coop
            servicePort: 3000

  - host: rsong.cf
    http:
      paths:
        - backend:
            serviceName: rsong-org
            servicePort: 80

  - host: wpdb-rchain-coop.tk
    http:
      paths:
        - backend:
            serviceName: db-adminer
            servicePort: 8080
