---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rchain-coop
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.global-static-ip-name: www-rchain-coop
    nginx.ingress.kubernetes.io/from-to-www-redirect: true
    certmanager.k8s.io/cluster-issuer: rchain-coop
    kubernetes.io/ingress.class: gce
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
  - host: rchain.coop
    http:
      paths:
        - backend:
            serviceName: rchain-coop
            servicePort: 3000
  - host: www.rchain.coop
    http:
      paths:
        - backend:
            serviceName: rchain-coop
            servicePort: 3000

  - host: developer.rchain.coop
    http:
      paths:
        - backend:
            serviceName: developer-rchain-coop
            servicePort: 3000

  - host: www.developer.rchain.coop
    http:
      paths:
        - backend:
            serviceName: developer-rchain-coop
            servicePort: 3000

  - host: blog.rchain.coop
    http:
      paths:
        - backend:
            serviceName: wordpress
            servicePort: 80

  - host: www.blog.rchain.coop
    http:
      paths:
        - backend:
            serviceName: wordpress
            servicePort: 80

  - host: dbadmin.rchain.coop
    http:
      paths:
        - backend:
            serviceName: db-adminer
            servicePort: 8080
  tls:
  - hosts:
      - rchain.coop
      - www.rchain.coop
      - blog.rchain.coop
      - developer.rchain.coop
    secretName: tls-letsencrypt-rchain-coop
