---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
    
data:
  PGUSER: {{ pg-user }}
  PGPASSWORD: {{ pg-password }}
  PGDB: {{ pg-database }}
  DB_URL: "postgresql://{{ pg-user }}:{{ pg-password }}:5432/{{ pg-database }}
