---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: crypto_flash
  PGUSER: crypto_flash
  PGPASSWORD: n04pC01xUEol9wjlIfzQ
  POSTGRES_PASSWORD: n04pC01xUEol9wjlIfzQ
  DB_URL: "postgresql://crypto_flash:n04pC01xUEol9wjlIfzQ@postgres:5432/crypto_flash
