---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: dev
  name: rchain-coop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rchain-coop
  template:
    metadata:
      labels:
        app: rchain-coop
    spec:
      containers:
      - name: rchain-coop
        image: kayvank/rchain.coop:1.0-94e93f6
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 2
